version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: live
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - Yonom
  labels:
  - Ready for Code Review
  versioning-strategy: increase
