version: "3.8"
services:
  db:
    container_name: db
    image: cockroachdb/cockroach:latest
    restart: always
    command: start-single-node --insecure
    networks:
      - correctlynet
    ports:
        - 26257:26257
        - 8080:8080

  flyway:
    container_name: flyway
    image: flyway/flyway:latest
    restart: on-failure
    command: migrate    
    depends_on:
      - db
    networks:
      - correctlynet
    volumes:
      - ./migrations:/flyway/sql:ro
      - ./flyway.conf:/flyway/conf/flyway.conf:ro

  distribution:
    container_name: distribution
    image: bretfisher/httping:latest
    command: -i 300 -t 300 -q -G http://localhost:3000/api/cron/distribution
    restart: always
    networks:
      - correctlynet

networks:
  correctlynet:
    name: correctlynet