ALTER TABLE "users" ADD creationdate TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE "attends" ADD creationdate TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE "courses" ADD creationdate TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE "reviews" ADD creationdate TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE "audits" ADD creationdate TIMESTAMPTZ NOT NULL DEFAULT NOW();