CREATE USER IF NOT EXISTS "backend";
CREATE USER IF NOT EXISTS "backend-dev";
CREATE USER IF NOT EXISTS "migrate" PASSWORD "MIGRATE_PASS";
CREATE USER IF NOT EXISTS "roach-ui" PASSWORD "ROACH_UI_PASS";
GRANT admin TO "roach-ui";
CREATE DATABASE IF NOT EXISTS app;
GRANT SELECT,INSERT,UPDATE,DELETE ON DATABASE app TO "backend","backend-dev","migrate";
GRANT CREATE,DROP ON DATABASE app TO "migrate";