version: "3.8"
services:
  app:
    container_name: app
    build:
      context: ./source
    restart: always
    volumes:
      - /home/correctly/config:/var/task/.keys:ro
    networks:
      - correctlynet
    ports:
      - 80:80

  db:
    container_name: db
    image: cockroachdb/cockroach:latest
    restart: always
    volumes:
    - ./data/node_1:/cockroach/cockroach-data
    command: start-single-node --insecure
    networks:
      - correctlynet
    ports:
        - 26257:26257
        - 8080:8080

  flyway:
    container_name: flyway
    image: flyway/flyway:latest
    restart: on-failure
    command: migrate    
    depends_on:
      - db
    networks:
      - correctlynet
    volumes:
      - ./source/migrations:/flyway/sql:ro
      - ./flyway.conf:/flyway/conf/flyway.conf:ro

  distribution:
    container_name: distribution
    image: bretfisher/httping:latest
    command: -i 300 -t 300 -q -G http://app:3000/api/cron/distribution
    restart: always
    depends_on:
      - app
    networks:
      - correctlynet

networks:
  correctlynet:
    name: correctlynet