name: Lint
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Add key.json
        run: echo "{}" >> .keys/key.json
      - name: Install dependencies
        run: npm i
      - name: Run ESLint
        run: npm run lint
      - name: Run build
        run: npm run build